
/**
 *
 * @author NILDO BUENO CORREIA FILHO  -
 * AXL- DESENVOLVIMENTO DE SISTEMAS
 * MSN: nil_bueno@hotmail.com
 * Created on 12/10/2011, 21:24:28
 */
package br.com.exl.backup.view;

import br.com.exl.infraWrite.WConfEmail;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author Melquisedeque
 */
public class ConfEmail extends javax.swing.JFrame {

    /** Creates new form ConfEmail */
    public ConfEmail() {
        initComponents();
        setSize(625, 490);
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("DADOS PARA WORKFLOW - NET BACKUP");
        DesabilitaCampos();
        ler_Dir();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf_assunto = new javax.swing.JTextField();
        tf_nome_re = new javax.swing.JTextField();
        pw_senha = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        tf_de = new javax.swing.JTextField();
        tf_nome_dest = new javax.swing.JTextField();
        tf_para = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_server_smtp = new javax.swing.JTextField();
        tf_login = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_porta_smtp = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Configurações"));

        jLabel2.setText("Email Origem");

        jLabel8.setText("Assunto");

        jLabel1.setText("Servidor SMTP");

        jLabel3.setText("Email Destino");

        jLabel4.setText("Origem de");

        jLabel5.setText("Destino");

        jLabel6.setText("Login");

        jLabel7.setText("Senha");

        jLabel10.setText("Porta Smtp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tf_assunto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_server_smtp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(tf_de, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(tf_login)
                            .addComponent(tf_para, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nome_dest)
                            .addComponent(tf_nome_re, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(pw_senha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(tf_porta_smtp))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_server_smtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10)
                    .addComponent(tf_porta_smtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pw_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_de, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nome_re, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_para, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tf_nome_dest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_assunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Menssagem"));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("ENVIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel9.setText("CONFIGURAÇÕES DE WORKFLOW");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-625)/2, (screenSize.height-490)/2, 625, 490);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
HabilitaCampos();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        SalvarConf();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfEmail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPasswordField pw_senha;
    private javax.swing.JTextField tf_assunto;
    private javax.swing.JTextField tf_de;
    private javax.swing.JTextField tf_login;
    private javax.swing.JTextField tf_nome_dest;
    private javax.swing.JTextField tf_nome_re;
    private javax.swing.JTextField tf_para;
    private javax.swing.JTextField tf_porta_smtp;
    private javax.swing.JTextField tf_server_smtp;
    // End of variables declaration//GEN-END:variables

    public void SalvarConf()

    {
     
       
    
        if(tf_server_smtp.getText().isEmpty() &  (tf_porta_smtp.getText().isEmpty()))
{JOptionPane.showMessageDialog(null,"Selecione os Diretórios Corretamente","Aviso",JOptionPane.WARNING_MESSAGE);}
else if(tf_server_smtp.getText() != null & (tf_porta_smtp.getText().isEmpty()))
{JOptionPane.showMessageDialog(null,"Voçê Selecionou um Diretorio de Análise, porém Não Selecionou um Diretório de Saida","Aviso",JOptionPane.WARNING_MESSAGE);}
else if (tf_server_smtp.getText().equalsIgnoreCase("\\") & (tf_porta_smtp.getText()!= null ))
{JOptionPane.showMessageDialog(null, "", "", JOptionPane.ERROR_MESSAGE);}
else if (tf_server_smtp.getText() != null & (tf_porta_smtp.getText().equalsIgnoreCase("\\") ))
{JOptionPane.showMessageDialog(null, "", "", JOptionPane.ERROR_MESSAGE);}
else if (tf_server_smtp.getText().equalsIgnoreCase("\\") & (tf_porta_smtp.getText().equalsIgnoreCase("\\") ))
{}
else if (tf_server_smtp.getText().isEmpty() & (tf_porta_smtp.getText()!= null ))
{JOptionPane.showMessageDialog(null,"Voçê Selecionou um Diretorio de Saída, porém Não Selecionou um Diretório de Análise","AVISO DO SISTEMA",JOptionPane.WARNING_MESSAGE);}

else if (tf_login.getText().isEmpty() & (pw_senha.getText().isEmpty()))
{JOptionPane.showMessageDialog(null,"Selecione os Diretórios Corretamente","Aviso",JOptionPane.WARNING_MESSAGE);}
else if(tf_login.getText() != null & (pw_senha.getText().isEmpty()))
{JOptionPane.showMessageDialog(null,"Voçê Selecionou um Diretorio de Análise, porém Não Selecionou um Diretório de Saida","Aviso",JOptionPane.WARNING_MESSAGE);}
else if (tf_login.getText().equalsIgnoreCase("\\") & (pw_senha.getText()!= null ))
{JOptionPane.showMessageDialog(null, "", "", JOptionPane.ERROR_MESSAGE);}
else if (tf_login.getText() != null & (pw_senha.getText().equalsIgnoreCase("\\") ))
{JOptionPane.showMessageDialog(null, "", "", JOptionPane.ERROR_MESSAGE);}
else if (tf_login.getText().equalsIgnoreCase("\\") & (pw_senha.getText().equalsIgnoreCase("\\") ))
{}
else if (tf_login.getText().isEmpty() & (pw_senha.getText()!= null ))
{JOptionPane.showMessageDialog(null,"Voçê Selecionou um Diretorio de Saída, porém Não Selecionou um Diretório de Análise","AVISO DO SISTEMA",JOptionPane.WARNING_MESSAGE);}

else if (tf_de.getText().isEmpty() & (tf_para.getText().isEmpty()))
{JOptionPane.showMessageDialog(null,"Selecione os Diretórios Corretamente","Aviso",JOptionPane.WARNING_MESSAGE);}
else if(tf_de.getText() != null & (tf_para.getText().isEmpty()))
{JOptionPane.showMessageDialog(null,"Voçê Selecionou um Diretorio de Análise, porém Não Selecionou um Diretório de Saida","Aviso",JOptionPane.WARNING_MESSAGE);}
else if (tf_de.getText().equalsIgnoreCase("\\") & (tf_para.getText()!= null ))
{JOptionPane.showMessageDialog(null, "", "", JOptionPane.ERROR_MESSAGE);}
else if (tf_de.getText() != null & (tf_para.getText().equalsIgnoreCase("\\") ))
{JOptionPane.showMessageDialog(null, "", "", JOptionPane.ERROR_MESSAGE);}
else if (tf_de.getText().equalsIgnoreCase("\\") & (tf_para.getText().equalsIgnoreCase("\\") ))
{}
else if (tf_de.getText().isEmpty() & (tf_para.getText()!= null ))
{JOptionPane.showMessageDialog(null,"Voçê Selecionou um Diretorio de Saída, porém Não Selecionou um Diretório de Análise","AVISO DO SISTEMA",JOptionPane.WARNING_MESSAGE);}

else if (tf_assunto.getText().isEmpty() & (jTextArea1.getText().isEmpty()))
{JOptionPane.showMessageDialog(null,"Selecione os Diretórios Corretamente","Aviso",JOptionPane.WARNING_MESSAGE);}
else if(tf_assunto.getText() != null & (jTextArea1.getText().isEmpty()))
{JOptionPane.showMessageDialog(null,"Voçê Selecionou um Diretorio de Análise, porém Não Selecionou um Diretório de Saida","Aviso",JOptionPane.WARNING_MESSAGE);}
else if (tf_assunto.getText().equalsIgnoreCase("\\") & (jTextArea1.getText()!= null ))
{JOptionPane.showMessageDialog(null, "", "", JOptionPane.ERROR_MESSAGE);}
else if (tf_assunto.getText() != null & (jTextArea1.getText().equalsIgnoreCase("\\") ))
{JOptionPane.showMessageDialog(null, "", "", JOptionPane.ERROR_MESSAGE);}
else if (tf_assunto.getText().equalsIgnoreCase("\\") & (jTextArea1.getText().equalsIgnoreCase("\\") ))
{}
else if (tf_assunto.getText().isEmpty() & (jTextArea1.getText()!= null ))
{JOptionPane.showMessageDialog(null,"Voçê Selecionou um Diretorio de Saída, porém Não Selecionou um Diretório de Análise","AVISO DO SISTEMA",JOptionPane.WARNING_MESSAGE);}

else{             
        WConfEmail.SalvaConfEmailByNILDO(tf_server_smtp.getText(), tf_porta_smtp.getText(), tf_de.getText(), tf_para.getText(), tf_nome_re.getText(),
                tf_nome_dest.getText(), tf_login.getText(),
                pw_senha.getText(), tf_assunto.getText(), jTextArea1.getText());
  }
}


    public void HabilitaCampos()
    {
        
    tf_server_smtp.setEditable(true);
    tf_porta_smtp.setEditable(true);
    tf_assunto.setEditable(true);
    tf_nome_dest.setEditable(true);
    tf_nome_re.setEditable(true);
    tf_login.setEditable(true);
    pw_senha.setEditable(true);
    tf_de.setEditable(true);
    tf_para.setEditable(true);
    jTextArea1.setEditable(true);
    
    }

    public void DesabilitaCampos(){

    tf_server_smtp.setEditable(false);
    tf_porta_smtp.setEditable(false);
    tf_assunto.setEditable(false);
    tf_nome_dest.setEditable(false);
    tf_nome_re.setEditable(false);
    tf_login.setEditable(false);
    pw_senha.setEditable(false);
    tf_de.setEditable(false);
    tf_para.setEditable(false);
    jTextArea1.setEditable(false);



    }

     public void ler_Dir(){

         File ler_servSmtp = new File  ("C:\\Windows\\ler_servSmtp.nbx");
        File ler_portaSmtp = new File ("C:\\Windows\\ler_portaSmtp.nbx");
        File ler_deEmail = new File   ("C:\\Windows\\ler_deEmail.nbx");
        File ler_paraEmail = new File ("C:\\Windows\\ler_paraEmail.nbx");
        File ler_nomeDe = new File    ("C:\\Windows\\ler_nomeDe.nbx");
        File ler_nomePara = new File  ("C:\\Windows\\ler_nomePara.nbx");
        File ler_login = new File     ("C:\\Windows\\ler_login.nbx");
        File ler_senha = new File     ("C:\\Windows\\ler_senha.nbx");
        File ler_assunto = new File   ("C:\\Windows\\ler_assunto.nbx");
        File ler_Menssagem = new File ("C:\\Windows\\ler_Menssagem.nbx");

//        File ler_servSmtp  = new File  ("C:\\Arquivos de programas\\Net Backup\\ENG\\03\\LerservSmtp.nbx");
//        File ler_portaSmtp = new File  ("C:\\Arquivos de programas\\Net Backup\\ENG\\03\\LerportaSmtp.nbx");
//        File ler_deEmail   = new File  ("C:\\Arquivos de programas\\Net Backup\\ENG\\03\\LerdeEmail.nbx");
//        File ler_paraEmail = new File  ("C:\\Arquivos de programas\\Net Backup\\ENG\\03\\LerparaEmail.nbx");
//        File ler_nomeDe    = new File  ("C:\\Arquivos de programas\\Net Backup\\ENG\\03\\LernomeDe.nbx");
//        File ler_nomePara  = new File  ("C:\\Arquivos de programas\\Net Backup\\ENG\\03\\LernomePara.nbx");
//        File ler_login     = new File  ("C:\\Arquivos de programas\\Net Backup\\ENG\\03\\Lerlogin.nbx");
//        File ler_senha     = new File  ("C:\\Arquivos de programas\\Net Backup\\ENG\\03\\Lersenha.nbx");
//        File ler_assunto   = new File  ("C:\\Arquivos de programas\\Net Backup\\ENG\\03\\Lerassunto.nbx");
//        File ler_Menssagem = new File  ("C:\\Arquivos de programas\\Net Backup\\ENG\\03\\LerMenssagem.nbx");


         FileInputStream fluxoArquivo = null;
         ObjectInputStream entradaObjeto = null;
         DataInputStream ob_Pri = null;

         FileInputStream fluxoArquivo1 = null;
         ObjectInputStream entradaObjeto1 = null;
         DataInputStream ob_Pri1 = null;

         FileInputStream fluxoArquivo2 = null;
         ObjectInputStream entradaObjeto2 = null;
         DataInputStream ob_Pri2 = null;

         FileInputStream fluxoArquivo3 = null;
         ObjectInputStream entradaObjeto3 = null;
         DataInputStream ob_Pri3 = null;

         FileInputStream fluxoArquivo4 = null;
         ObjectInputStream entradaObjeto4 = null;
         DataInputStream ob_Pri4 = null;

         FileInputStream fluxoArquivo5 = null;
         ObjectInputStream entradaObjeto5 = null;
         DataInputStream ob_Pri5 = null;

         FileInputStream fluxoArquivo6 = null;
         ObjectInputStream entradaObjeto6 = null;
         DataInputStream ob_Pri6 = null;

         FileInputStream fluxoArquivo7 = null;
         ObjectInputStream entradaObjeto7 = null;
         DataInputStream ob_Pri7 = null;

         FileInputStream fluxoArquivo8 = null;
         ObjectInputStream entradaObjeto8 = null;
         DataInputStream ob_Pri8 = null;

         FileInputStream fluxoArquivo9 = null;
         ObjectInputStream entradaObjeto9 = null;
         DataInputStream ob_Pri9 = null;

        try{
            
        fluxoArquivo = new FileInputStream(ler_servSmtp);
        entradaObjeto = new ObjectInputStream(fluxoArquivo);
        ob_Pri = new DataInputStream( fluxoArquivo);

        fluxoArquivo1 = new FileInputStream(ler_portaSmtp);
        entradaObjeto1 = new ObjectInputStream(fluxoArquivo1);
        ob_Pri1 = new DataInputStream( fluxoArquivo1);

        fluxoArquivo2 = new FileInputStream(ler_deEmail);
        entradaObjeto2 = new ObjectInputStream(fluxoArquivo2);
        ob_Pri2 = new DataInputStream( fluxoArquivo2);

        fluxoArquivo3 = new FileInputStream(ler_paraEmail);
        entradaObjeto3 = new ObjectInputStream(fluxoArquivo3);
        ob_Pri3 = new DataInputStream( fluxoArquivo3);

        fluxoArquivo4 = new FileInputStream(ler_nomeDe);
        entradaObjeto4 = new ObjectInputStream(fluxoArquivo4);
        ob_Pri4 = new DataInputStream( fluxoArquivo4);

        fluxoArquivo5 = new FileInputStream(ler_nomePara);
        entradaObjeto5 = new ObjectInputStream(fluxoArquivo5);
        ob_Pri5 = new DataInputStream( fluxoArquivo5);

        fluxoArquivo6 = new FileInputStream(ler_login);
        entradaObjeto6 = new ObjectInputStream(fluxoArquivo6);
        ob_Pri6 = new DataInputStream( fluxoArquivo6);

        fluxoArquivo7 = new FileInputStream(ler_senha);
        entradaObjeto7 = new ObjectInputStream(fluxoArquivo7);
        ob_Pri7 = new DataInputStream( fluxoArquivo7);

        fluxoArquivo8 = new FileInputStream(ler_assunto);
        entradaObjeto8 = new ObjectInputStream(fluxoArquivo8);
        ob_Pri8 = new DataInputStream( fluxoArquivo8);

        fluxoArquivo9 = new FileInputStream(ler_Menssagem);
        entradaObjeto9 = new ObjectInputStream(fluxoArquivo9);
        ob_Pri9 = new DataInputStream( fluxoArquivo9);

        String textDir = (String) entradaObjeto.readObject();
        String textDir1 = (String) entradaObjeto1.readObject();
        String textDir2 = (String) entradaObjeto2.readObject();
        String textDir3 = (String) entradaObjeto3.readObject();
        String textDir4 = (String) entradaObjeto4.readObject();
        String textDir5 = (String) entradaObjeto5.readObject();
        String textDir6 = (String) entradaObjeto6.readObject();
        String textDir7 = (String) entradaObjeto7.readObject();
        String textDir8 = (String) entradaObjeto8.readObject();
        String textDir9 = (String) entradaObjeto9.readObject();
         
        tf_server_smtp.setText(textDir);
        tf_porta_smtp.setText(textDir1);
        tf_de.setText(textDir2);
        tf_para.setText(textDir3);
        tf_nome_re.setText(textDir4);
        tf_nome_dest.setText(textDir5);
        tf_login.setText(textDir6);
        pw_senha.setText(textDir7);
        tf_assunto.setText(textDir8);
        jTextArea1.setText(textDir9);

        entradaObjeto.close();
        ob_Pri.close();

        entradaObjeto1.close();
        ob_Pri1.close();

        entradaObjeto2.close();
        ob_Pri2.close();

        entradaObjeto3.close();
        ob_Pri3.close();

        entradaObjeto4.close();
        ob_Pri4.close();

        entradaObjeto5.close();
        ob_Pri5.close();

        entradaObjeto6.close();
        ob_Pri6.close();

        entradaObjeto7.close();
        ob_Pri7.close();

        entradaObjeto8.close();
        ob_Pri8.close();
        
        entradaObjeto9.close();
        ob_Pri9.close();

        }catch(Exception e){ 
       
       
                   }
        }
}