
/**
 *
 * @author NILDO BUENO CORREIA FILHO 
 * NB- DESENVOLVIMENTO DE SISTEMAS
 * EMAIL: nildojava@gmail.com    
 *        nildin82@hotmail.com
 * CEL: 8115-7490
 * Created on 22/07/2011, 12:52:12
 */

package br.com.exl.backup.view;


public class Sobreview extends javax.swing.JFrame {

    /** Creates new form Sobreview */
    public Sobreview() {
        initComponents();
        setSize(546, 434);
        setLocationRelativeTo(null);
        setTitle("SOBRE NET BACKUP");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("NB SISTEMAS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel2.setText("Versão Beta");

        jLabel3.setText("Copyrigth (C) 2003 - 2011  Nildo Bueno, LLC.");

        jLabel4.setText("All Rigth Reserved.");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setText("\nDESENVOLVIDO POR:  Nildo Bueno Corrêia Filho\n\nProgramador Java - PL\\SQL\nTecnico de Informartica -\nAdministrador de Redes  Microsoft - Linux - Unix \n\nContato\nEmail: nildojava@gmail.com - nildin82@hotmail.com\nCel: 8115 - 7490  \n \nATENÇÃO OS BUGS EXISTENTES, \nSERÃO CORRIGIDOS NA PRÓXIMA VERSÃO. ");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("NET BACKUP", jPanel1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("\n\nADS, ADB,  ASM, ASP, ASPX, AU3, SH, AL8, DXF, DAT, BAK, \nASF, JSP, EPS, PPTX, MDBX, BIN, BMP, DIB, RLE, CGM, PCT,\nTIF, VML, AVI, ASF, ASX, BSH, CMD, NT, C, ML, MLI, SML,\nTHY,  CMAKE, CBL, CBD,  CDB, WMF, ZIP, CXX, CC, CS, CSS,\nD, CDC, COB, H, HPP, HXX, CPP, DIFF, PACTH, F, FOR, F90,\nF95, F2K, HS, LHS, AS, DOCX, ORM, JS, DLL, FLA, MID, \nMAX, CGI, HTML, MOV, MVB, JAVA, DBC, ASS, ISO, JAR, PER,\nMF, XLSX, INI, MDF, MDS, FORM, JCCFG3 TIME, CONF, WAB, \nMF, JSP,  KIX,   LSP, LSX, PPT, SWF, PTX, LAS, SHTML, \nSHTM, XHTML, INF, REG, URL, ISS, EMF, LISP, LUA, MAK, M,\nNFO, NSI, NSH, PAS, INC, PL, LOG, PIC, OLE, OGG, RAR, \nTIF, TTF, WRI, JAVA, JS, MDB, DBX, BMP, RM, GIF,  JRXML,\nMI, WMA, WAX, WAV, ODT,  ODS, ODP, ODB, ODD,  JC, MP3, \nAVI, QXD, WAV, VOB, MPG, ICO, PMG, NBX, RPM,  HTM,\nPM, PLX,  PHP,  PHP3,   PHTML, PS,   PS1, PROPERTIES,\nPY, PYW, R,  RC,  RB,  RBW,  SCM, SCMD,  SS,  SD,\nTCL, TEX, TXT, XML, CSV, SQL, PDF, XLS, CLASS, DWG,  NRG, OCX,\nVB, BUILD,  VBSX,  V,  VHD,  VHDL,  XSML,  XSL,  XSD,  KML");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("EXTENSÕES DE ARQUIVOS SUPORTADOS", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-546)/2, (screenSize.height-434)/2, 546, 434);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sobreview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables

}
